Allow searching for exact values as well as regexps
Currently, the search methods expect their arguments to be regexps. Trying to
search for e.g. strings gives the following error message:

  TypeError: type mismatch: String given
          from palletjack/lib/palletjack.rb:46:in `=~'

Change the search methods to look at the type of their argument, using =~ for
regexps and comparing the string representations for other types.